### ISSUE TITLE
Migrating from sodiumoxide to *ring*

### ISSUE THREAD

**Issue by jimmycuadra** [cryptosphere/macaroons-rs#17]
What do you think about the idea of migrating this crate's crypto primitives to the ones from *ring*? I'm not sure if it supports everything that is needed yet. But it would be nice to be able to drop the libsodium dependency.

**Comment by tarcieri** [comment]
In general I prefer *ring* to sodiumoxide, however the Macaroons format presently uses Salsa20Poly1305, which *ring* does not support.
